jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      node_10_x:
        node_version: 10.x
      node_9_x:
        node_version: 9.x
      node_8_x:
        node_version: 8.x
      node_6_x:
        node_version: 6.x
    maxParallel: 4
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node.js'
  - bash: npm i
    displayName: 'Install dependencies'
  - bash: npm run lint
    displayName: Run linter
  - bash: npm run coveralls -- -c
    displayName: 'Run tests'
  - bash: npm run typescript
    displayName: Check types
