name: Benchmark

on:
  pull_request_target:
    types: [labeled]

jobs:
  benchmark:
    if: ${{ github.event.label.name == 'benchmark' }}
    runs-on: ubuntu-latest
    outputs:
      PR-BENCH-14: ${{ steps.benchmark-pr.outputs.BENCH_RESULT14 }}
      PR-BENCH-16: ${{ steps.benchmark-pr.outputs.BENCH_RESULT16 }}
      PR-BENCH-17: ${{ steps.benchmark-pr.outputs.BENCH_RESULT17 }}
      MAIN-BENCH-14: ${{ steps.benchmark-main.outputs.BENCH_RESULT14 }}
      MAIN-BENCH-16: ${{ steps.benchmark-main.outputs.BENCH_RESULT16 }}
      MAIN-BENCH-17: ${{ steps.benchmark-main.outputs.BENCH_RESULT17 }}
    strategy:
      matrix:
        node-version: [14, 16, 17]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install --only=production --ignore-scripts

      - name: Run benchmark
        id: benchmark-pr
        run: |
          npm run --silent benchmark > ./bench-result.md
          result=$(awk '/requests in/' ./bench-result.md)
          echo "::set-output name=BENCH_RESULT${{matrix.node-version}}::$result"

      # main benchmark
      - uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Install
        run: |
          npm install --only=production --ignore-scripts

      - name: Run benchmark
        id: benchmark-main
        run: |
          npm run --silent benchmark > ./bench-result.md
          result=$(awk '/requests in/' ./bench-result.md)
          echo "::set-output name=BENCH_RESULT${{matrix.node-version}}::$result"

  output-benchmark:
    needs: [benchmark]
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            **Node**: 14
            **PR**: ${{ needs.benchmark.outputs.PR-BENCH-14 }}
            **MAIN**: ${{ needs.benchmark.outputs.MAIN-BENCH-14 }}
            
            ---
            
            **Node**: 16
            **PR**: ${{ needs.benchmark.outputs.PR-BENCH-16 }}
            **MAIN**: ${{ needs.benchmark.outputs.MAIN-BENCH-16 }}
            
            ---
            
            **Node**: 17
            **PR**: ${{ needs.benchmark.outputs.PR-BENCH-17 }}
            **MAIN**: ${{ needs.benchmark.outputs.MAIN-BENCH-17 }}
            
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            benchmark
          github_token: ${{ secrets.GITHUB_TOKEN }}
