name: ci

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install
        run: |
          npm install --ignore-scripts

      - name: Lint code
        run: |
          npm run lint

  coverage-nix:
    uses: ./.github/workflows/coverage-nix.yml
  coverage-win:
    uses: ./.github/workflows/coverage-win.yml

  test:
    needs: [linter, coverage-nix, coverage-win]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14, 16, 17]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v3.0.1
        id: check-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Install
        run: |
          npm install --ignore-scripts

      - name: Check licenses
        run: |
          npm run license-checker

      - name: Run tests
        run: |
          npm run test:ci

  automerge:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - uses: actions/cache@v3.0.1
        id: check-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install fastify
        run: |
          npm install --ignore-scripts
      - name: install webpack stack
        run: |
          cd test/bundler/webpack && npm install
      - name: Test webpack bundle
        run: |
          cd test/bundler/webpack && npm run test
      - name: install esbuild stack
        run: |
          cd test/bundler/esbuild && npm install
      - name: Test esbuild bundle
        run: |
          cd test/bundler/esbuild && npm run test
