name: integration Alternative Runtimes

on:
  push:
    branches:
     - main
     - next
     - 'v*'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  install-production:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    strategy:
      matrix:
        os: [ubuntu-latest]
        runtime: [nsolid]
        node-version: [20]
        pnpm-version: [8]
        include:
          - nsolid-version: 5
            node-version: 20
            runtime: nsolid
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: nodesource/setup-nsolid@v1
        if: ${{ matrix.runtime == 'nsolid' }}
        with:
          node-version: ${{ matrix.node-version }}
          nsolid-version: ${{ matrix.nsolid-version }}

      - name: Install Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Install Production
        run: |
          pnpm install --prod

      - name: Run server
        run: |
          node integration/server.js &

      - name: Test
        if: ${{ success() }}
        run: |
          bash integration/test.sh
