name: package-manager-ci

on:
  push:
    branches:
      - master

jobs:
  pnpm:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Maintenance and active LTS
        node-version: [10.x, 12.x]
        os: [ubuntu-16.04]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install with pnpm
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer | node
          pnpm install

      - name: Run tests
        run: |
          pnpm run test

  yarn:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Maintenance and active LTS
        node-version: [10.x, 12.x]
        os: [ubuntu-16.04]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install with yarn
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          yarn install --ignore-engines

      - name: Run tests
        run: |
          yarn run test
