name: package-manager-ci

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pnpm:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    strategy:
      matrix:
        # Maintenance and active LTS
        node-version: [20, 22, 24]
        os: [ubuntu-latest]
        pnpm-version: [8]

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Install with pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: ${{ matrix.pnpm-version }}

      - run: pnpm install --ignore-scripts

      - name: Run tests
        run: |
          pnpm run test:ci
        env:
          NODE_OPTIONS: no-network-family-autoselection

  yarn:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    strategy:
      matrix:
        # Maintenance and active LTS
        node-version: [20, 22, 24]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Install with yarn
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          yarn install --ignore-engines --ignore-scripts

      - run: yarn

      - name: Run tests
        run: |
          yarn run test:ci
        env:
          NODE_OPTIONS: no-network-family-autoselection
